# Generated by Django 4.1.1 on 2022-09-14 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('tanks', 'Танки'), ('hills', 'Хилы'), ('DD', 'ДД'), ('merchants', 'Торговцы'), ('gildmasters', 'Гилдмастеры'), ('cvestgivers', 'Квестгиверы'), ('blacksmith', 'Кузнецы'), ('tenners', 'Кожевники'), ('potioncookers', 'Зельевары'), ('spellmasters', 'Мастера заклинаний')], default='tanks', max_length=16)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeclarationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('accepted', models.BooleanField(default=False)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.declaration')),
            ],
        ),
    ]
