# Generated by Django 4.1.1 on 2022-09-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_declaration_date_declaration_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivation',
            name='user_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='secret_key',
            field=models.CharField(default='cqn*07ujsud%3w8@uqwlq*q=yg%x=lr+y@ba501%-kdqbr(d=m', max_length=256),
        ),
    ]
