# Generated by Django 4.1.1 on 2022-09-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_declaration_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='upload',
            field=models.FileField(default=None, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='secret_key',
            field=models.CharField(default='=xp!v+&tw439@8l-*!=-6634e*d0g&(l0e14$^kf_o&rw&*9!*', max_length=256),
        ),
    ]
