# Generated by Django 4.1.1 on 2022-09-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_declaration_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='upload',
            field=models.FileField(blank=True, default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='secret_key',
            field=models.CharField(default='8f=7z4-)*lj3^(1b+dvnbp1^!j#wvvofpc5ju@c*w6fssjef#g', max_length=256),
        ),
    ]
