# Generated by Django 4.1.1 on 2022-09-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_declaration_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='upload',
            field=models.FileField(blank=True, default='', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='secret_key',
            field=models.CharField(default='3lmtu)u%ogeosi+7$84838*n28kmtq!$eq32h879&udu-jzk5k', max_length=256),
        ),
    ]
